version: '3.9'
networks:
  basic:
services:
  front:
    build:
      context: ./
      dockerfile: Dockerfile
      target: front
    container_name: greaterwms_front
    restart: always
    privileged: true
    ports:
      - '8080:8080'
    depends_on:
      - backend
    networks:
      - basic
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
      target: backend
    container_name: greaterwms_backend
    restart: always
    privileged: true
    volumes:
      - ./:/GreaterWMS/:rw
      - ./supervisord.conf:/etc/supervisor/supervisord.conf
    ports:
      - '8008:8008'
    environment:
      PYTHONUNBUFFERED: 1
    depends_on:
      - redis
    networks:
      - basic
  worker:
    build:
      context: ./
      dockerfile: Dockerfile
      target: backend
    container_name: greaterwms_worker
    restart: always
    privileged: true
    volumes:
      - ./:/GreaterWMS/:rw
      - ./supervisord_worker.conf:/etc/supervisor/supervisord.conf
    environment:
      PYTHONUNBUFFERED: 1
    depends_on:
      - backend
      - redis
    networks:
      - basic
  beat:
    build:
      context: ./
      dockerfile: Dockerfile
      target: backend
    container_name: greaterwms_beat
    restart: always
    privileged: true
    volumes:
      - ./:/GreaterWMS/:rw
      - ./supervisord_beat.conf:/etc/supervisor/supervisord.conf
    environment:
      PYTHONUNBUFFERED: 1
    depends_on:
      - worker
      - redis
    networks:
      - basic
  redis:
    image: "redis:alpine"
    container_name: greaterwms_redis
    networks:
      - basic
