version: '3.9'
networks:
  basic:
services:
  front:
    build:
      context: ./
      dockerfile: Dockerfile
      target: front
    container_name: greaterwms_front
    restart: always
    privileged: true
    ports:
      - '8080:8080'
    depends_on:
      - backend
    networks:
      - basic
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
      target: backend
    container_name: greaterwms_backend
    restart: always
    privileged: true
    volumes:
      - ./:/GreaterWMS/:rw
      - ./supervisord.conf:/etc/supervisor/supervisord.conf
    ports:
      - '8008:8008'
    environment:
      PYTHONUNBUFFERED: 1
    networks:
      - basic
  # redis:
  #   image: redis:latest
  #   restart: "no"
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./redis.conf:/etc/redis/redis.conf 
  #     - ./data:/data      
  #   command: redis-server /etc/redis/redis.conf 
  #   privileged: true
