# Generated by Django 4.1.2 on 2024-02-23 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.CharField(max_length=255, verbose_name='Shop Warehouse id')),
                ('platform_name', models.CharField(max_length=255, verbose_name='Shop Warehouse Name')),
                ('supplier', models.CharField(max_length=255, verbose_name='Supplier')),
                ('openid', models.CharField(max_length=255, verbose_name='Openid')),
                ('creater', models.CharField(max_length=255, verbose_name='Who Created')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Update Time')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopwarehouse', to='shop.listmodel')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopwarehouse', to='warehouse.listmodel')),
            ],
            options={
                'verbose_name': 'Shop Warehouse',
                'verbose_name_plural': 'Shop Warehouse',
                'db_table': 'shopwarehouse',
                'ordering': ['platform_name'],
            },
        ),
    ]
