# Generated by Django 4.1.2 on 2024-02-23 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.CharField(max_length=255, verbose_name='Platform ID')),
                ('platform_sku', models.CharField(max_length=255, verbose_name='Platform SKU')),
                ('goods_code', models.CharField(max_length=255, verbose_name='Goods code')),
                ('sync_status', models.BigIntegerField(default=1, verbose_name='Sync Status')),
                ('sync_message', models.CharField(default='', max_length=255, verbose_name='Sync Message')),
                ('sync_time', models.DateTimeField(blank=True, null=True, verbose_name='Sync Time')),
                ('platform_data', models.TextField(default='', verbose_name='Platform Data')),
                ('supplier', models.CharField(max_length=255, verbose_name='Supplier')),
                ('openid', models.CharField(max_length=255, verbose_name='Openid')),
                ('creater', models.CharField(max_length=255, verbose_name='Who Created')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Update Time')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopsku', to='shop.listmodel')),
            ],
            options={
                'verbose_name': 'Shop Sku',
                'verbose_name_plural': 'Shop Sku',
                'db_table': 'shopsku',
                'ordering': ['platform_sku'],
            },
        ),
    ]
