# Generated by Django 4.1.2 on 2024-02-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listmodel',
            name='sync_message',
            field=models.CharField(default='', max_length=255, verbose_name='Sync Message'),
        ),
        migrations.AddField(
            model_name='listmodel',
            name='sync_status',
            field=models.BigIntegerField(default=1, verbose_name='Sync Status'),
        ),
        migrations.AddField(
            model_name='listmodel',
            name='sync_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sync Time'),
        ),
    ]
