# Generated by Django 4.1.2 on 2024-02-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsku', '0002_listmodel_sync_message_listmodel_sync_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listmodel',
            name='platform_data',
            field=models.TextField(default='', verbose_name='Platform Data'),
        ),
    ]
