# Generated by Django 4.1.2 on 2024-02-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255, verbose_name='Shop Name')),
                ('shop_type', models.CharField(max_length=255, verbose_name='Shop Type')),
                ('shop_data', models.CharField(max_length=1024, verbose_name='Shop Data')),
                ('sync', models.BooleanField(default=False, verbose_name='Sync Store')),
                ('stock_threshold', models.BigIntegerField(default=0, verbose_name='Stock Threshold')),
                ('supplier', models.CharField(max_length=255, verbose_name='Supplier')),
                ('openid', models.CharField(max_length=255, verbose_name='Openid')),
                ('creater', models.CharField(max_length=255, verbose_name='Who Created')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Update Time')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shop',
                'db_table': 'shop',
                'ordering': ['shop_name'],
            },
        ),
    ]
