# Generated by Django 4.1.2 on 2024-02-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listmodel',
            name='stock_threshold',
            field=models.BigIntegerField(default=0, verbose_name='Stock Threshold'),
        ),
    ]
