# Generated by Django 4.1.2 on 2024-02-23 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.CharField(max_length=255, verbose_name='Platform Order ID')),
                ('platform_warehouse_id', models.CharField(max_length=255, verbose_name='Platform Warehouse ID')),
                ('posting_number', models.CharField(max_length=255, verbose_name='Posting Number')),
                ('dn_code', models.CharField(max_length=255, verbose_name='DN Code')),
                ('order_data', models.TextField(verbose_name='Order Data')),
                ('order_products', models.TextField(verbose_name='Order Products')),
                ('stockbin_data', models.TextField(verbose_name='Stockbin Data')),
                ('order_time', models.DateTimeField(verbose_name='Order Time')),
                ('shipment_time', models.DateTimeField(verbose_name='Shipment Time')),
                ('status', models.BigIntegerField(default=1, verbose_name='Status')),
                ('handle_status', models.BigIntegerField(default=1, verbose_name='Handle Status')),
                ('handle_message', models.CharField(max_length=255, verbose_name='Handle Message')),
                ('supplier', models.CharField(max_length=255, verbose_name='Supplier')),
                ('openid', models.CharField(max_length=255, verbose_name='Openid')),
                ('creater', models.CharField(max_length=255, verbose_name='Who Created')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Update Time')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoporder', to='shop.listmodel')),
            ],
            options={
                'verbose_name': 'Shop Order',
                'verbose_name_plural': 'Shop Order',
                'db_table': 'shoporder',
                'ordering': ['-id'],
            },
        ),
    ]
