# Generated by Django 4.1.2 on 2024-02-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoporder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listmodel',
            name='order_label',
            field=models.CharField(default='', max_length=255, verbose_name='Order Label'),
        ),
    ]
